module FunLang.Ast

// =============================================================================
// Position Information
// =============================================================================

type Position = {
    Line: int
    Column: int
    File: string option
}

let noPos = { Line = 1; Column = 1; File = None }

// =============================================================================
// Located<'T> - Wrapper for AST nodes with position information
// =============================================================================

/// Wrapper type that attaches position information to any node
type Located<'T> = {
    Node: 'T
    Pos: Position
}

/// Helper functions for Located<'T>
module Located =
    /// Create a Located value with the given position
    let create (pos: Position) (node: 'T) : Located<'T> =
        { Node = node; Pos = pos }

    /// Create a Located value with no position (for synthesized nodes)
    let noLoc (node: 'T) : Located<'T> =
        { Node = node; Pos = noPos }

    /// Transform the node inside a Located value
    let map (f: 'T -> 'U) (located: Located<'T>) : Located<'U> =
        { Node = f located.Node; Pos = located.Pos }

    /// Extract the node from a Located value
    let node (located: Located<'T>) : 'T =
        located.Node

    /// Extract the position from a Located value
    let pos (located: Located<'T>) : Position =
        located.Pos

// =============================================================================
// Note: Token type is generated by FsLexYacc in Parser.fs
// Use FunLang.GeneratedParser.token or FunLang.Parser.Token
// =============================================================================

// =============================================================================
// Literals
// =============================================================================

type Literal =
    | LInt of int
    | LBool of bool
    | LString of string
    | LUnit

// =============================================================================
// Operators
// =============================================================================

type BinaryOp =
    | Add | Sub | Mul | Div | Mod
    | Eq | Neq | Lt | Gt | Lte | Gte
    | And | Or

type UnaryOp =
    | Neg | Not

// =============================================================================
// AST (Abstract Syntax Tree)
// =============================================================================

/// Expression AST with position-tracked sub-expressions
type Expr =
    | ELiteral of Literal
    | EVariable of string
    | EBinaryOp of BinaryOp * Located<Expr> * Located<Expr>
    | EUnaryOp of UnaryOp * Located<Expr>
    | ELet of string * Located<Expr> * Located<Expr>
    | ELetRec of string * Located<Expr> * Located<Expr>
    | ELambda of string * Located<Expr>
    | EApply of Located<Expr> * Located<Expr>
    | EIf of Located<Expr> * Located<Expr> * Located<Expr>
    | ETuple of Located<Expr> list
    | EList of Located<Expr> list
    | ECons of Located<Expr> * Located<Expr>
    | EBlock of Located<Expr> list
    | EMatch of Located<Expr> * (Located<Pattern> * Located<Expr> option * Located<Expr>) list
    | EConstructor of string * Located<Expr> option

/// Pattern AST with position-tracked sub-patterns
and Pattern =
    | PWildcard
    | PVariable of string
    | PLiteral of Literal
    | PTuple of Located<Pattern> list
    | PList of Located<Pattern> list
    | PCons of Located<Pattern> * Located<Pattern>
    | PConstructor of string * Located<Pattern> option

// =============================================================================
// Located Expression and Pattern type aliases
// =============================================================================

/// Located expression - Expr with position information
type LExpr = Located<Expr>

/// Located pattern - Pattern with position information
type LPattern = Located<Pattern>

// =============================================================================
// Values (Runtime)
// =============================================================================

type Value =
    | VInt of int
    | VBool of bool
    | VString of string
    | VUnit
    | VTuple of Value list
    | VList of Value list
    | VClosure of string * LExpr * Env
    | VRecClosure of string * string * LExpr * Env
    | VConstructed of string * Value option  // Constructor name and optional argument value

and Env = Map<string, Value>

// =============================================================================
// Type Expressions (for constructor argument types)
// =============================================================================

/// Type expression in constructor definitions
/// Used to represent compound types like 'a * List 'a
type TypeExpr =
    | TEVar of string                    // 'a, 'b, etc.
    | TEName of string                   // int, bool, etc.
    | TEApp of string * TypeExpr list    // List 'a, Option int, etc.
    | TETuple of TypeExpr list           // 'a * 'b, etc.

// =============================================================================
// Type Definitions (User-Defined Types)
// =============================================================================

/// Constructor definition: (name, optional argument type expression)
/// e.g., ("Some", Some (TEVar "a")) for Some of 'a
///       ("None", None) for None
///       ("Cons", Some (TETuple [TEVar "a"; TEApp ("List", [TEVar "a"])])) for Cons of 'a * List 'a
type ConstructorDef = string * TypeExpr option

/// Type definition (discriminated union)
/// e.g., type Option 'a = None | Some of 'a
type TypeDef = {
    Name: string              // "Option"
    TypeParams: string list   // ["a"]
    Constructors: ConstructorDef list  // [("None", None); ("Some", Some (TEVar "a"))]
}

/// Program = type definitions + main expression
type Program = {
    TypeDefs: TypeDef list
    MainExpr: LExpr option
}

// =============================================================================
// Helper module for creating unlocated AST nodes (for tests and synthesized nodes)
// =============================================================================

/// Helpers for creating unlocated expressions and patterns
module Unlocated =
    /// Wrap an expression with no position
    let expr (e: Expr) : LExpr = Located.noLoc e

    /// Wrap a pattern with no position
    let pattern (p: Pattern) : LPattern = Located.noLoc p

    /// Create unlocated EBinaryOp
    let binOp op (l: Expr) (r: Expr) : Expr =
        EBinaryOp(op, Located.noLoc l, Located.noLoc r)

    /// Create unlocated EUnaryOp
    let unaryOp op (e: Expr) : Expr =
        EUnaryOp(op, Located.noLoc e)

    /// Create unlocated ELet
    let elet name (value: Expr) (body: Expr) : Expr =
        ELet(name, Located.noLoc value, Located.noLoc body)

    /// Create unlocated ELetRec
    let eletrec name (value: Expr) (body: Expr) : Expr =
        ELetRec(name, Located.noLoc value, Located.noLoc body)

    /// Create unlocated ELambda
    let elambda param (body: Expr) : Expr =
        ELambda(param, Located.noLoc body)

    /// Create unlocated EApply
    let eapply (func: Expr) (arg: Expr) : Expr =
        EApply(Located.noLoc func, Located.noLoc arg)

    /// Create unlocated EIf
    let eif (cond: Expr) (thenBr: Expr) (elseBr: Expr) : Expr =
        EIf(Located.noLoc cond, Located.noLoc thenBr, Located.noLoc elseBr)

    /// Create unlocated ETuple
    let etuple (exprs: Expr list) : Expr =
        ETuple(List.map Located.noLoc exprs)

    /// Create unlocated EList
    let elist (exprs: Expr list) : Expr =
        EList(List.map Located.noLoc exprs)

    /// Create unlocated ECons
    let econs (head: Expr) (tail: Expr) : Expr =
        ECons(Located.noLoc head, Located.noLoc tail)

    /// Create unlocated EBlock
    let eblock (exprs: Expr list) : Expr =
        EBlock(List.map Located.noLoc exprs)

    /// Create unlocated EMatch
    let ematch (scrutinee: Expr) (cases: (Pattern * Expr option * Expr) list) : Expr =
        let locatedCases =
            cases |> List.map (fun (p, g, e) ->
                (Located.noLoc p, Option.map Located.noLoc g, Located.noLoc e))
        EMatch(Located.noLoc scrutinee, locatedCases)

    /// Create unlocated EConstructor
    let econstructor name (arg: Expr option) : Expr =
        EConstructor(name, Option.map Located.noLoc arg)

    /// Create unlocated PTuple
    let ptuple (patterns: Pattern list) : Pattern =
        PTuple(List.map Located.noLoc patterns)

    /// Create unlocated PList
    let plist (patterns: Pattern list) : Pattern =
        PList(List.map Located.noLoc patterns)

    /// Create unlocated PCons
    let pcons (head: Pattern) (tail: Pattern) : Pattern =
        PCons(Located.noLoc head, Located.noLoc tail)

    /// Create unlocated PConstructor
    let pconstructor name (arg: Pattern option) : Pattern =
        PConstructor(name, Option.map Located.noLoc arg)

// =============================================================================
// Display module - Convert Located AST to plain format for display
// =============================================================================

/// Display-friendly AST types (names match Expr/Pattern for compatible output)
module Display =
    // Reference the original types before defining shadowing types
    type OrigExpr = Expr
    type OrigPattern = Pattern

    /// Display expression - mirrors Expr but without Located wrappers
    type Expr =
        | ELiteral of Literal
        | EVariable of string
        | EBinaryOp of BinaryOp * Expr * Expr
        | EUnaryOp of UnaryOp * Expr
        | ELet of string * Expr * Expr
        | ELetRec of string * Expr * Expr
        | ELambda of string * Expr
        | EApply of Expr * Expr
        | EIf of Expr * Expr * Expr
        | ETuple of Expr list
        | EList of Expr list
        | ECons of Expr * Expr
        | EBlock of Expr list
        | EMatch of Expr * (Pattern * Expr option * Expr) list
        | EConstructor of string * Expr option

    /// Display pattern - mirrors Pattern but without Located wrappers
    and Pattern =
        | PWildcard
        | PVariable of string
        | PLiteral of Literal
        | PTuple of Pattern list
        | PList of Pattern list
        | PCons of Pattern * Pattern
        | PConstructor of string * Pattern option

    /// Convert LExpr to display-friendly format
    let rec ofExpr (lexpr: LExpr) : Expr =
        match lexpr.Node with
        | OrigExpr.ELiteral lit -> ELiteral lit
        | OrigExpr.EVariable name -> EVariable name
        | OrigExpr.EBinaryOp (op, left, right) -> EBinaryOp (op, ofExpr left, ofExpr right)
        | OrigExpr.EUnaryOp (op, operand) -> EUnaryOp (op, ofExpr operand)
        | OrigExpr.ELet (name, value, body) -> ELet (name, ofExpr value, ofExpr body)
        | OrigExpr.ELetRec (name, value, body) -> ELetRec (name, ofExpr value, ofExpr body)
        | OrigExpr.ELambda (param, body) -> ELambda (param, ofExpr body)
        | OrigExpr.EApply (func, arg) -> EApply (ofExpr func, ofExpr arg)
        | OrigExpr.EIf (cond, thenBr, elseBr) -> EIf (ofExpr cond, ofExpr thenBr, ofExpr elseBr)
        | OrigExpr.ETuple exprs -> ETuple (List.map ofExpr exprs)
        | OrigExpr.EList exprs -> EList (List.map ofExpr exprs)
        | OrigExpr.ECons (head, tail) -> ECons (ofExpr head, ofExpr tail)
        | OrigExpr.EBlock exprs -> EBlock (List.map ofExpr exprs)
        | OrigExpr.EMatch (scrutinee, cases) ->
            let displayCases =
                cases |> List.map (fun (pat, guard, body) ->
                    (ofPattern pat, Option.map ofExpr guard, ofExpr body))
            EMatch (ofExpr scrutinee, displayCases)
        | OrigExpr.EConstructor (name, arg) -> EConstructor (name, Option.map ofExpr arg)

    and ofPattern (lpat: LPattern) : Pattern =
        match lpat.Node with
        | OrigPattern.PWildcard -> PWildcard
        | OrigPattern.PVariable name -> PVariable name
        | OrigPattern.PLiteral lit -> PLiteral lit
        | OrigPattern.PTuple pats -> PTuple (List.map ofPattern pats)
        | OrigPattern.PList pats -> PList (List.map ofPattern pats)
        | OrigPattern.PCons (head, tail) -> PCons (ofPattern head, ofPattern tail)
        | OrigPattern.PConstructor (name, arg) -> PConstructor (name, Option.map ofPattern arg)
