module FunLang.Ast

// =============================================================================
// Position Information
// =============================================================================

type Position = {
    Line: int
    Column: int
    File: string option
}

let noPos = { Line = 0; Column = 0; File = None }

// =============================================================================
// Note: Token type is generated by FsLexYacc in Parser.fs
// Use FunLang.GeneratedParser.token or FunLang.Parser.Token
// =============================================================================

// =============================================================================
// Literals
// =============================================================================

type Literal =
    | LInt of int
    | LBool of bool
    | LString of string
    | LUnit

// =============================================================================
// Operators
// =============================================================================

type BinaryOp =
    | Add | Sub | Mul | Div | Mod
    | Eq | Neq | Lt | Gt | Lte | Gte
    | And | Or

type UnaryOp =
    | Neg | Not

// =============================================================================
// AST (Abstract Syntax Tree)
// =============================================================================

type Expr =
    | ELiteral of Literal
    | EVariable of string
    | EBinaryOp of BinaryOp * Expr * Expr
    | EUnaryOp of UnaryOp * Expr
    | ELet of string * Expr * Expr
    | ELetRec of string * Expr * Expr
    | ELambda of string * Expr
    | EApply of Expr * Expr
    | EIf of Expr * Expr * Expr
    | ETuple of Expr list
    | EList of Expr list
    | ECons of Expr * Expr
    | EBlock of Expr list
    | EMatch of Expr * (Pattern * Expr option * Expr) list
    | EConstructor of string * Expr option  // Constructor name and optional argument

and Pattern =
    | PWildcard
    | PVariable of string
    | PLiteral of Literal
    | PTuple of Pattern list
    | PList of Pattern list
    | PCons of Pattern * Pattern
    | PConstructor of string * Pattern option

// =============================================================================
// Values (Runtime)
// =============================================================================

type Value =
    | VInt of int
    | VBool of bool
    | VString of string
    | VUnit
    | VTuple of Value list
    | VList of Value list
    | VClosure of string * Expr * Env
    | VRecClosure of string * string * Expr * Env
    | VConstructed of string * Value option  // Constructor name and optional argument value

and Env = Map<string, Value>
